### ISSUE TITLE
serialization error when player join, (command nodes ?)

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#253]
Got a weird error that i can't reproduce when i joined the server while working on commands

```sh
> node -r dotenv/config src/index.js | pino-human

0000000525            world  I  World loaded { world: 'floor1', mobs: 6048, items: 896, teleportation_stones: 10 }
0000002410            index  I  Listening { address: '::', family: 'IPv6', port: 25565 }
0000003894            debug  I  Server listening at http://127.0.0.1:4242 {}
0000003894            debug  I  Arborist https://aresrpg-arborist.netlify.app/http%3A%2F%2F127.0.0.1%3A4242%2Fbehavior {}
0000013698 player/resource_  I  Ressource pack status { status: [ 'ACCEPTED', 3 ] }
(node:22529) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 state listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
file:///home/sceat/dev/aresrpg/aresrpg/src/index.js:253
  throw error
  ^

TypeError: Serialization error for play.toClient : SizeOf error for undefined : Cannot read property 'min_present' of undefined
    at eval (eval at compile (/home/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/compiler.js:245:12), <anonymous>:679:40)
    at eval (eval at compile (/home/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/compiler.js:245:12), <anonymous>:683:25)
    at eval (eval at compile (/home/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/compiler.js:245:12), <anonymous>:692:23)
    at eval (eval at compile (/home/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/compiler.js:245:12), <anonymous>:698:19)
    at eval (eval at compile (/home/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/compiler.js:245:12), <anonymous>:707:17)
    at eval (eval at compile (/home/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/compiler.js:245:12), <anonymous>:710:13)
    at eval (eval at compile (/home/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/compiler.js:245:12), <anonymous>:712:11)
    at Object.packet_declare_commands (eval at compile (/home/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/compiler.js:245:12), <anonymous>:715:9)
    at eval (eval at compile (/home/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/compiler.js:245:12), <anonymous>:2267:72)
    at packet (eval at compile (/home/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/compiler.js:245:12), <anonymous>:2346:9) {
  field: 'play.toClient'
}
```

It's about a 3 layer deep command `/enjin send <player> <amount>`

![image](https://user-images.githubusercontent.com/11330271/128635320-5944b2d4-40b5-466e-ab0f-43ca6f5b47c6.png)

**Comment by Sceat** [comment]
Actually it happens indeed when a command has 3 layer deep

**Comment by Sceat** [comment]
was missing properties
```
	  extraNodeData: {
	    name: 'kAres amount',
	    parser: 'brigadier:integer',
	    properties: { flags: { min_present: false, max_present: false } },
	  },
```
