### ISSUE TITLE
Getting weird serialization client crash

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#329]
It happens sometimes while logging in for an unknow reason on [that](https://github.com/aresrpg/aresrpg/tree/sceat/new-lvl) branch 🤔 

```
0000008008          context  E  Client error {
  code: 'ERR_OUT_OF_RANGE',
  field: 'play.toClient',
  stack: 'RangeError [ERR_OUT_OF_RANGE]: Serialization error for play.toClient : Write error for undefined : The value of "value" is out of range. It must be >= -32768 and <= 32767. Received 32768\n' +
    '    at new NodeError (node:internal/errors:371:5)\n' +
    '    at checkInt (node:internal/buffer:72:11)\n' +
    '    at writeU_Int16BE (node:internal/buffer:832:3)\n' +
    '    at Buffer.writeInt16BE (node:internal/buffer:894:10)\n' +
    '    at Object.writer [as i16] (/Users/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/datatypes/numeric.js:89:25)\n' +
    '    at Object.packet_entity_move_look (eval at compile (/Users/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1316:25)\n' +
    '    at eval (eval at compile (/Users/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2294:72)\n' +
    '    at packet (eval at compile (/Users/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2344:9)\n' +
    '    at CompiledProtodef.write (/Users/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/compiler.js:76:12)\n' +
    '    at e.message (/Users/sceat/dev/aresrpg/aresrpg/node_modules/protodef/src/compiler.js:102:25)',
  type: 'Error'
}
```

![image](https://user-images.githubusercontent.com/11330271/137819038-3d05e462-c6de-4d2b-8dc2-4f52fd92ba85.png)

**Comment by DeltaEvo** [comment]
Did you had multiple accounts connected when this happened ?
