### ISSUE TITLE
Killing a mob with no loots throws an error

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#364]
```
TypeError: Types[mob.mob].loots is not iterable
    at EventEmitter.<anonymous> (file:///Users/sceat/dev/aresrpg/aresrpg/src/mobs/loot.js:14:55)
    at EventEmitter.emit (node:events:394:28)
    at file:///Users/sceat/dev/aresrpg/aresrpg/src/mobs/damage.js:61:22
    at HAsyncIterator.reduce (/Users/sceat/dev/aresrpg/aresrpg/node_modules/iterator-helper/dist/async-iterator/HAsyncIterator.js:208:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Sceat** [comment]
like killing a npc #339

**Comment by Sceat** [comment]
see #369
